/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as Char123LocaleChar125RouteRouteImport } from './routes/{-$locale}/route'
import { Route as Char123LocaleChar125rootLayoutRouteRouteImport } from './routes/{-$locale}/(root-layout)/route'
import { Route as Char123LocaleChar125centeredLayoutRouteRouteImport } from './routes/{-$locale}/(centered-layout)/route'
import { Route as Char123LocaleChar125rootLayoutIndexRouteImport } from './routes/{-$locale}/(root-layout)/index'
import { Route as ApiHealthLiveRouteImport } from './routes/[_]api/health/live'
import { Route as Char123LocaleChar125rootLayoutauthRouteRouteImport } from './routes/{-$locale}/(root-layout)/(auth)/route'
import { Route as Char123LocaleChar125centeredLayoutguestRouteRouteImport } from './routes/{-$locale}/(centered-layout)/(guest)/route'
import { Route as Char123LocaleChar125rootLayoutTermsOfServiceIndexRouteImport } from './routes/{-$locale}/(root-layout)/terms-of-service/index'
import { Route as Char123LocaleChar125rootLayoutPrivacyPolicyIndexRouteImport } from './routes/{-$locale}/(root-layout)/privacy-policy/index'
import { Route as Char123LocaleChar125rootLayoutPlaygroundIndexRouteImport } from './routes/{-$locale}/(root-layout)/playground/index'
import { Route as Char123LocaleChar125rootLayoutErrorIndexRouteImport } from './routes/{-$locale}/(root-layout)/error/index'
import { Route as Char123LocaleChar125rootLayoutauthDashboardIndexRouteImport } from './routes/{-$locale}/(root-layout)/(auth)/dashboard/index'
import { Route as Char123LocaleChar125centeredLayoutguestSignInIndexRouteImport } from './routes/{-$locale}/(centered-layout)/(guest)/sign-in/index'
import { Route as Char123LocaleChar125centeredLayoutguestCreateAnAccountIndexRouteImport } from './routes/{-$locale}/(centered-layout)/(guest)/create-an-account/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125RouteRoute =
  Char123LocaleChar125RouteRouteImport.update({
    id: '/{-$locale}',
    path: '/{-$locale}',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125rootLayoutRouteRoute =
  Char123LocaleChar125rootLayoutRouteRouteImport.update({
    id: '/(root-layout)',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125centeredLayoutRouteRoute =
  Char123LocaleChar125centeredLayoutRouteRouteImport.update({
    id: '/(centered-layout)',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125rootLayoutIndexRoute =
  Char123LocaleChar125rootLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125rootLayoutRouteRoute,
  } as any)
const ApiHealthLiveRoute = ApiHealthLiveRouteImport.update({
  id: '/_api/health/live',
  path: '/_api/health/live',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125rootLayoutauthRouteRoute =
  Char123LocaleChar125rootLayoutauthRouteRouteImport.update({
    id: '/(auth)',
    getParentRoute: () => Char123LocaleChar125rootLayoutRouteRoute,
  } as any)
const Char123LocaleChar125centeredLayoutguestRouteRoute =
  Char123LocaleChar125centeredLayoutguestRouteRouteImport.update({
    id: '/(guest)',
    getParentRoute: () => Char123LocaleChar125centeredLayoutRouteRoute,
  } as any)
const Char123LocaleChar125rootLayoutTermsOfServiceIndexRoute =
  Char123LocaleChar125rootLayoutTermsOfServiceIndexRouteImport.update({
    id: '/terms-of-service/',
    path: '/terms-of-service/',
    getParentRoute: () => Char123LocaleChar125rootLayoutRouteRoute,
  } as any)
const Char123LocaleChar125rootLayoutPrivacyPolicyIndexRoute =
  Char123LocaleChar125rootLayoutPrivacyPolicyIndexRouteImport.update({
    id: '/privacy-policy/',
    path: '/privacy-policy/',
    getParentRoute: () => Char123LocaleChar125rootLayoutRouteRoute,
  } as any)
const Char123LocaleChar125rootLayoutPlaygroundIndexRoute =
  Char123LocaleChar125rootLayoutPlaygroundIndexRouteImport.update({
    id: '/playground/',
    path: '/playground/',
    getParentRoute: () => Char123LocaleChar125rootLayoutRouteRoute,
  } as any)
const Char123LocaleChar125rootLayoutErrorIndexRoute =
  Char123LocaleChar125rootLayoutErrorIndexRouteImport.update({
    id: '/error/',
    path: '/error/',
    getParentRoute: () => Char123LocaleChar125rootLayoutRouteRoute,
  } as any)
const Char123LocaleChar125rootLayoutauthDashboardIndexRoute =
  Char123LocaleChar125rootLayoutauthDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => Char123LocaleChar125rootLayoutauthRouteRoute,
  } as any)
const Char123LocaleChar125centeredLayoutguestSignInIndexRoute =
  Char123LocaleChar125centeredLayoutguestSignInIndexRouteImport.update({
    id: '/sign-in/',
    path: '/sign-in/',
    getParentRoute: () => Char123LocaleChar125centeredLayoutguestRouteRoute,
  } as any)
const Char123LocaleChar125centeredLayoutguestCreateAnAccountIndexRoute =
  Char123LocaleChar125centeredLayoutguestCreateAnAccountIndexRouteImport.update(
    {
      id: '/create-an-account/',
      path: '/create-an-account/',
      getParentRoute: () => Char123LocaleChar125centeredLayoutguestRouteRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/{-$locale}': typeof Char123LocaleChar125rootLayoutauthRouteRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_api/health/live': typeof ApiHealthLiveRoute
  '/{-$locale}/': typeof Char123LocaleChar125rootLayoutIndexRoute
  '/{-$locale}/error/': typeof Char123LocaleChar125rootLayoutErrorIndexRoute
  '/{-$locale}/playground/': typeof Char123LocaleChar125rootLayoutPlaygroundIndexRoute
  '/{-$locale}/privacy-policy/': typeof Char123LocaleChar125rootLayoutPrivacyPolicyIndexRoute
  '/{-$locale}/terms-of-service/': typeof Char123LocaleChar125rootLayoutTermsOfServiceIndexRoute
  '/{-$locale}/create-an-account/': typeof Char123LocaleChar125centeredLayoutguestCreateAnAccountIndexRoute
  '/{-$locale}/sign-in/': typeof Char123LocaleChar125centeredLayoutguestSignInIndexRoute
  '/{-$locale}/dashboard/': typeof Char123LocaleChar125rootLayoutauthDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/{-$locale}': typeof Char123LocaleChar125rootLayoutIndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_api/health/live': typeof ApiHealthLiveRoute
  '/{-$locale}/error': typeof Char123LocaleChar125rootLayoutErrorIndexRoute
  '/{-$locale}/playground': typeof Char123LocaleChar125rootLayoutPlaygroundIndexRoute
  '/{-$locale}/privacy-policy': typeof Char123LocaleChar125rootLayoutPrivacyPolicyIndexRoute
  '/{-$locale}/terms-of-service': typeof Char123LocaleChar125rootLayoutTermsOfServiceIndexRoute
  '/{-$locale}/create-an-account': typeof Char123LocaleChar125centeredLayoutguestCreateAnAccountIndexRoute
  '/{-$locale}/sign-in': typeof Char123LocaleChar125centeredLayoutguestSignInIndexRoute
  '/{-$locale}/dashboard': typeof Char123LocaleChar125rootLayoutauthDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$locale}': typeof Char123LocaleChar125RouteRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/{-$locale}/(centered-layout)': typeof Char123LocaleChar125centeredLayoutRouteRouteWithChildren
  '/{-$locale}/(root-layout)': typeof Char123LocaleChar125rootLayoutRouteRouteWithChildren
  '/{-$locale}/(centered-layout)/(guest)': typeof Char123LocaleChar125centeredLayoutguestRouteRouteWithChildren
  '/{-$locale}/(root-layout)/(auth)': typeof Char123LocaleChar125rootLayoutauthRouteRouteWithChildren
  '/_api/health/live': typeof ApiHealthLiveRoute
  '/{-$locale}/(root-layout)/': typeof Char123LocaleChar125rootLayoutIndexRoute
  '/{-$locale}/(root-layout)/error/': typeof Char123LocaleChar125rootLayoutErrorIndexRoute
  '/{-$locale}/(root-layout)/playground/': typeof Char123LocaleChar125rootLayoutPlaygroundIndexRoute
  '/{-$locale}/(root-layout)/privacy-policy/': typeof Char123LocaleChar125rootLayoutPrivacyPolicyIndexRoute
  '/{-$locale}/(root-layout)/terms-of-service/': typeof Char123LocaleChar125rootLayoutTermsOfServiceIndexRoute
  '/{-$locale}/(centered-layout)/(guest)/create-an-account/': typeof Char123LocaleChar125centeredLayoutguestCreateAnAccountIndexRoute
  '/{-$locale}/(centered-layout)/(guest)/sign-in/': typeof Char123LocaleChar125centeredLayoutguestSignInIndexRoute
  '/{-$locale}/(root-layout)/(auth)/dashboard/': typeof Char123LocaleChar125rootLayoutauthDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$locale}'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/_api/health/live'
    | '/{-$locale}/'
    | '/{-$locale}/error/'
    | '/{-$locale}/playground/'
    | '/{-$locale}/privacy-policy/'
    | '/{-$locale}/terms-of-service/'
    | '/{-$locale}/create-an-account/'
    | '/{-$locale}/sign-in/'
    | '/{-$locale}/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/{-$locale}'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/_api/health/live'
    | '/{-$locale}/error'
    | '/{-$locale}/playground'
    | '/{-$locale}/privacy-policy'
    | '/{-$locale}/terms-of-service'
    | '/{-$locale}/create-an-account'
    | '/{-$locale}/sign-in'
    | '/{-$locale}/dashboard'
  id:
    | '__root__'
    | '/{-$locale}'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/{-$locale}/(centered-layout)'
    | '/{-$locale}/(root-layout)'
    | '/{-$locale}/(centered-layout)/(guest)'
    | '/{-$locale}/(root-layout)/(auth)'
    | '/_api/health/live'
    | '/{-$locale}/(root-layout)/'
    | '/{-$locale}/(root-layout)/error/'
    | '/{-$locale}/(root-layout)/playground/'
    | '/{-$locale}/(root-layout)/privacy-policy/'
    | '/{-$locale}/(root-layout)/terms-of-service/'
    | '/{-$locale}/(centered-layout)/(guest)/create-an-account/'
    | '/{-$locale}/(centered-layout)/(guest)/sign-in/'
    | '/{-$locale}/(root-layout)/(auth)/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LocaleChar125RouteRoute: typeof Char123LocaleChar125RouteRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiHealthLiveRoute: typeof ApiHealthLiveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}': {
      id: '/{-$locale}'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/(root-layout)': {
      id: '/{-$locale}/(root-layout)'
      path: ''
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125rootLayoutRouteRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/(centered-layout)': {
      id: '/{-$locale}/(centered-layout)'
      path: ''
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125centeredLayoutRouteRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/(root-layout)/': {
      id: '/{-$locale}/(root-layout)/'
      path: '/'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125rootLayoutIndexRouteImport
      parentRoute: typeof Char123LocaleChar125rootLayoutRouteRoute
    }
    '/_api/health/live': {
      id: '/_api/health/live'
      path: '/_api/health/live'
      fullPath: '/_api/health/live'
      preLoaderRoute: typeof ApiHealthLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/(root-layout)/(auth)': {
      id: '/{-$locale}/(root-layout)/(auth)'
      path: ''
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125rootLayoutauthRouteRouteImport
      parentRoute: typeof Char123LocaleChar125rootLayoutRouteRoute
    }
    '/{-$locale}/(centered-layout)/(guest)': {
      id: '/{-$locale}/(centered-layout)/(guest)'
      path: ''
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125centeredLayoutguestRouteRouteImport
      parentRoute: typeof Char123LocaleChar125centeredLayoutRouteRoute
    }
    '/{-$locale}/(root-layout)/terms-of-service/': {
      id: '/{-$locale}/(root-layout)/terms-of-service/'
      path: '/terms-of-service'
      fullPath: '/{-$locale}/terms-of-service/'
      preLoaderRoute: typeof Char123LocaleChar125rootLayoutTermsOfServiceIndexRouteImport
      parentRoute: typeof Char123LocaleChar125rootLayoutRouteRoute
    }
    '/{-$locale}/(root-layout)/privacy-policy/': {
      id: '/{-$locale}/(root-layout)/privacy-policy/'
      path: '/privacy-policy'
      fullPath: '/{-$locale}/privacy-policy/'
      preLoaderRoute: typeof Char123LocaleChar125rootLayoutPrivacyPolicyIndexRouteImport
      parentRoute: typeof Char123LocaleChar125rootLayoutRouteRoute
    }
    '/{-$locale}/(root-layout)/playground/': {
      id: '/{-$locale}/(root-layout)/playground/'
      path: '/playground'
      fullPath: '/{-$locale}/playground/'
      preLoaderRoute: typeof Char123LocaleChar125rootLayoutPlaygroundIndexRouteImport
      parentRoute: typeof Char123LocaleChar125rootLayoutRouteRoute
    }
    '/{-$locale}/(root-layout)/error/': {
      id: '/{-$locale}/(root-layout)/error/'
      path: '/error'
      fullPath: '/{-$locale}/error/'
      preLoaderRoute: typeof Char123LocaleChar125rootLayoutErrorIndexRouteImport
      parentRoute: typeof Char123LocaleChar125rootLayoutRouteRoute
    }
    '/{-$locale}/(root-layout)/(auth)/dashboard/': {
      id: '/{-$locale}/(root-layout)/(auth)/dashboard/'
      path: '/dashboard'
      fullPath: '/{-$locale}/dashboard/'
      preLoaderRoute: typeof Char123LocaleChar125rootLayoutauthDashboardIndexRouteImport
      parentRoute: typeof Char123LocaleChar125rootLayoutauthRouteRoute
    }
    '/{-$locale}/(centered-layout)/(guest)/sign-in/': {
      id: '/{-$locale}/(centered-layout)/(guest)/sign-in/'
      path: '/sign-in'
      fullPath: '/{-$locale}/sign-in/'
      preLoaderRoute: typeof Char123LocaleChar125centeredLayoutguestSignInIndexRouteImport
      parentRoute: typeof Char123LocaleChar125centeredLayoutguestRouteRoute
    }
    '/{-$locale}/(centered-layout)/(guest)/create-an-account/': {
      id: '/{-$locale}/(centered-layout)/(guest)/create-an-account/'
      path: '/create-an-account'
      fullPath: '/{-$locale}/create-an-account/'
      preLoaderRoute: typeof Char123LocaleChar125centeredLayoutguestCreateAnAccountIndexRouteImport
      parentRoute: typeof Char123LocaleChar125centeredLayoutguestRouteRoute
    }
  }
}

interface Char123LocaleChar125centeredLayoutguestRouteRouteChildren {
  Char123LocaleChar125centeredLayoutguestCreateAnAccountIndexRoute: typeof Char123LocaleChar125centeredLayoutguestCreateAnAccountIndexRoute
  Char123LocaleChar125centeredLayoutguestSignInIndexRoute: typeof Char123LocaleChar125centeredLayoutguestSignInIndexRoute
}

const Char123LocaleChar125centeredLayoutguestRouteRouteChildren: Char123LocaleChar125centeredLayoutguestRouteRouteChildren =
  {
    Char123LocaleChar125centeredLayoutguestCreateAnAccountIndexRoute:
      Char123LocaleChar125centeredLayoutguestCreateAnAccountIndexRoute,
    Char123LocaleChar125centeredLayoutguestSignInIndexRoute:
      Char123LocaleChar125centeredLayoutguestSignInIndexRoute,
  }

const Char123LocaleChar125centeredLayoutguestRouteRouteWithChildren =
  Char123LocaleChar125centeredLayoutguestRouteRoute._addFileChildren(
    Char123LocaleChar125centeredLayoutguestRouteRouteChildren,
  )

interface Char123LocaleChar125centeredLayoutRouteRouteChildren {
  Char123LocaleChar125centeredLayoutguestRouteRoute: typeof Char123LocaleChar125centeredLayoutguestRouteRouteWithChildren
}

const Char123LocaleChar125centeredLayoutRouteRouteChildren: Char123LocaleChar125centeredLayoutRouteRouteChildren =
  {
    Char123LocaleChar125centeredLayoutguestRouteRoute:
      Char123LocaleChar125centeredLayoutguestRouteRouteWithChildren,
  }

const Char123LocaleChar125centeredLayoutRouteRouteWithChildren =
  Char123LocaleChar125centeredLayoutRouteRoute._addFileChildren(
    Char123LocaleChar125centeredLayoutRouteRouteChildren,
  )

interface Char123LocaleChar125rootLayoutauthRouteRouteChildren {
  Char123LocaleChar125rootLayoutauthDashboardIndexRoute: typeof Char123LocaleChar125rootLayoutauthDashboardIndexRoute
}

const Char123LocaleChar125rootLayoutauthRouteRouteChildren: Char123LocaleChar125rootLayoutauthRouteRouteChildren =
  {
    Char123LocaleChar125rootLayoutauthDashboardIndexRoute:
      Char123LocaleChar125rootLayoutauthDashboardIndexRoute,
  }

const Char123LocaleChar125rootLayoutauthRouteRouteWithChildren =
  Char123LocaleChar125rootLayoutauthRouteRoute._addFileChildren(
    Char123LocaleChar125rootLayoutauthRouteRouteChildren,
  )

interface Char123LocaleChar125rootLayoutRouteRouteChildren {
  Char123LocaleChar125rootLayoutauthRouteRoute: typeof Char123LocaleChar125rootLayoutauthRouteRouteWithChildren
  Char123LocaleChar125rootLayoutIndexRoute: typeof Char123LocaleChar125rootLayoutIndexRoute
  Char123LocaleChar125rootLayoutErrorIndexRoute: typeof Char123LocaleChar125rootLayoutErrorIndexRoute
  Char123LocaleChar125rootLayoutPlaygroundIndexRoute: typeof Char123LocaleChar125rootLayoutPlaygroundIndexRoute
  Char123LocaleChar125rootLayoutPrivacyPolicyIndexRoute: typeof Char123LocaleChar125rootLayoutPrivacyPolicyIndexRoute
  Char123LocaleChar125rootLayoutTermsOfServiceIndexRoute: typeof Char123LocaleChar125rootLayoutTermsOfServiceIndexRoute
}

const Char123LocaleChar125rootLayoutRouteRouteChildren: Char123LocaleChar125rootLayoutRouteRouteChildren =
  {
    Char123LocaleChar125rootLayoutauthRouteRoute:
      Char123LocaleChar125rootLayoutauthRouteRouteWithChildren,
    Char123LocaleChar125rootLayoutIndexRoute:
      Char123LocaleChar125rootLayoutIndexRoute,
    Char123LocaleChar125rootLayoutErrorIndexRoute:
      Char123LocaleChar125rootLayoutErrorIndexRoute,
    Char123LocaleChar125rootLayoutPlaygroundIndexRoute:
      Char123LocaleChar125rootLayoutPlaygroundIndexRoute,
    Char123LocaleChar125rootLayoutPrivacyPolicyIndexRoute:
      Char123LocaleChar125rootLayoutPrivacyPolicyIndexRoute,
    Char123LocaleChar125rootLayoutTermsOfServiceIndexRoute:
      Char123LocaleChar125rootLayoutTermsOfServiceIndexRoute,
  }

const Char123LocaleChar125rootLayoutRouteRouteWithChildren =
  Char123LocaleChar125rootLayoutRouteRoute._addFileChildren(
    Char123LocaleChar125rootLayoutRouteRouteChildren,
  )

interface Char123LocaleChar125RouteRouteChildren {
  Char123LocaleChar125centeredLayoutRouteRoute: typeof Char123LocaleChar125centeredLayoutRouteRouteWithChildren
  Char123LocaleChar125rootLayoutRouteRoute: typeof Char123LocaleChar125rootLayoutRouteRouteWithChildren
}

const Char123LocaleChar125RouteRouteChildren: Char123LocaleChar125RouteRouteChildren =
  {
    Char123LocaleChar125centeredLayoutRouteRoute:
      Char123LocaleChar125centeredLayoutRouteRouteWithChildren,
    Char123LocaleChar125rootLayoutRouteRoute:
      Char123LocaleChar125rootLayoutRouteRouteWithChildren,
  }

const Char123LocaleChar125RouteRouteWithChildren =
  Char123LocaleChar125RouteRoute._addFileChildren(
    Char123LocaleChar125RouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  Char123LocaleChar125RouteRoute: Char123LocaleChar125RouteRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiHealthLiveRoute: ApiHealthLiveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
