import process from "node:process";

import { createEnv } from "@t3-oss/env-core";
import { z } from "zod";

console.debug("⏳ [ENV_WEB_SERVER] Loading environment variables...", {
  SOURCE_COMMIT: process.env.SOURCE_COMMIT
});

export const ENV_WEB_SERVER = createEnv({
  emptyStringAsUndefined: true,
  runtimeEnv: process.env,
  server: {
    NODE_ENV: z.enum(["development", "production"]).default("development"),
    SOURCE_COMMIT: z.string().min(1).default("unknown"), // autogenerated by Coolify, needs to be manually set otherwise
    IS_BUILD: z.stringbool().default(false) // set to 'true' during build, can be used to conditionally disable features that should only run during runtime and not during build/prerendering
  }
});

console.debug("✅ [ENV_WEB_SERVER] Successfully loaded environment variables.");
