export const GENERATED_CI_WORKFLOW =
  [
    "name: CI",
    "",
    "on:",
    "  push:",
    "    branches: [main]",
    "  pull_request:",
    "    branches: [main]",
    "",
    "permissions:",
    "  contents: read",
    "",
    "jobs:",
    "  quality:",
    "    runs-on: ubuntu-latest",
    "    timeout-minutes: 20",
    "    steps:",
    "      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7",
    "      - uses: pnpm/action-setup@ea17c68df8912ef543352723c149a84f56e3d413 # v6.1.0",
    "      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6",
    "        with:",
    "          node-version: 24",
    "          cache: pnpm",
    "      - run: pnpm install --frozen-lockfile",
    "      - name: Prepare environment",
    "        shell: bash",
    "        run: cp packages/env/.env.example packages/env/.env",
    "      - run: pnpm exec vp run check",
    "      - run: pnpm exec vp run test:unit:run",
    "      - name: Install Chromium",
    "        working-directory: apps/web",
    "        run: pnpm exec vp exec playwright install --with-deps chromium",
    "      - run: pnpm exec vp run test:e2e:run",
    "      - run: pnpm exec vp run build"
  ].join("\n") + "\n";
